#!/usr/bin/env python
import subprocess
import sys
import os

os.environ['PYTHONIOENCODING'] = 'utf-8'
os.chdir('E:\\')

script = r'E:\mechforge_ai\run_main.py'
result = subprocess.run([sys.executable, script], env={**os.environ, 'PYTHONIOENCODING': 'utf-8'})
sys.exit(result.returncode)
